### ISSUE TITLE
the geojson model building is rendered twice

### ISSUE THREAD

**Issue by stiangglanda** [openindoormap/openindoormaps#7]
- the first time as a background building
- the second time as the geojson model(as intended)

we need to exclude it from beieng rendered as a Background building
![Image](https://github.com/user-attachments/assets/db76790d-8b9a-4584-97e7-cf12c736f401)
![Image](https://github.com/user-attachments/assets/7e5ddada-5a64-44ae-8370-d4dd0181b95e)

**Comment by KnotzerIO** [comment]
add filter for this building and also remove redudant source declaration
![grafik](https://github.com/user-attachments/assets/a73c01a6-13e6-4dc6-ad40-f25595a15191)
